fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    module_data: "https://github.com/ripienaar/puppet-module-data.git"
    consul: 'https://github.com/bashtoni/puppet-consul.git'
    jenkins:
      repo: 'https://github.com/madAndroid/puppet-jenkins.git'
      ref: 'v1.3.1'
    jenkins_job_builder:
      repo: 'https://github.com/madAndroid/puppet-jenkins_job_builder.git'
      ref: 'v1.1.0-fork'

  forge_modules:
    java:
      repo: puppetlabs-java
      ref: '1.2.0'
    nginx:
      repo: jfryman/nginx
      ref: '0.2.6'
    concat:
      repo: puppetlabs/concat
      ref: '1.2.0'

    firewall: 'puppetlabs/firewall'
    staging: 'nanliu/staging'
    inifile: 'puppetlabs/inifile'
    epel: 'stahnma/epel'
    sudo: 'saz/sudo'

  symlinks:
    profiles: "#{source_dir}/localmodules/profiles"
    roles: "#{source_dir}/localmodules/roles"
    data: "#{source_dir}/localmodules/data"
