fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    module_data: "https://github.com/ripienaar/puppet-module-data.git"
    jenkins:
      repo: 'https://github.com/madAndroid/puppet-jenkins.git'
      ref: 'v1.3.1'
    jenkins_job_builder:
      repo: 'https://github.com/madAndroid/puppet-jenkins_job_builder.git'
      ref: 'v1.1.0-fork'

  forge_modules:
    java:
      repo: puppetlabs-java
      ref: '1.2.0'
    nginx:
      repo: jfryman/nginx
      ref: '0.2.6'
    concat:
      repo: puppetlabs/concat
      ref: '1.2.0'

    firewall: 'puppetlabs/firewall'

  symlinks:
    role_jenkins_ci_server: "#{source_dir}/localmodules/role_jenkins_ci_server"
    role_vagrant_host: "#{source_dir}/localmodules/role_vagrant_host"
    role_consul: "#{source_dir}/localmodules/role_consul"
    defaults: "#{source_dir}/localmodules/defaults"
