HOSTS:
  centos6:
    roles:
      - master
    platform: el-6-x86_64
    image: centos:centos6
    hypervisor: docker
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'mkdir -p /root/.ssh'
      - 'yum install -y tar gcc ruby-devel git'

CONFIG:
  type: foss
  log_level: verbose
  forward_ssh_agent: true
